name: Daily EPG Enrichment

on:
  workflow_dispatch:
  push:
    paths:
      - 'epg.xml'
      - 'scripts/enrich_epg.py'

jobs:
  enrich-epg:
    runs-on: ubuntu-latest

    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      pythonLocation: /opt/hostedtoolcache/Python/3.13.5/x64
      PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.13.5/x64/lib/pkgconfig
      Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.13.5/x64
      Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.13.5/x64
      Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.13.5/x64
      LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.13.5/x64/lib

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.13.5
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.5

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp lxml requests

      - name: Backup existing EPG
        run: cp epg.xml epg_yesterday.xml || true

      - name: Run enrich_epg.py
        run: |
          python scripts/enrich_epg.py epg.xml epg_updated.xml \
            --async \
            --landscape-only \
            --language en \
            --target-channels 403788 403674 403837 403794 403620 403772 403655 403847 403576

      - name: Replace original EPG if enriched file exists
        run: |
          if [ -f epg_updated.xml ]; then
            mv epg_updated.xml epg.xml
            echo "✅ EPG updated successfully."
          else
            echo "⚠️ epg_updated.xml not found. Enrichment may have failed."
            exit 1
          fi