name: Enrich EPG

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  enrich:
    runs-on: ubuntu-latest

    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx lxml aiohttp tmdbsimple

      - name: Enrich EPG XML
        run: |
          python scripts/enrich_epg.py epg.xml epg_updated.xm
      
      - name: Replace old EPG
        run: mv epg_updated.xml epg.xml