name: Enrich and Replace EPG

on:
  workflow_dispatch:

jobs:
  enrich_epg:
    runs-on: ubuntu-latest

    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install aiohttp tqdm

      - name: Debug - List Initial XML Files
        run: ls -lh *.xml

      - name: Enrich EPG XML
        run: |
          python scripts/enrich_epg.py epg.xml epg_updated.xml \
            --async \
            --landscape-only \
            --language en

      - name: Debug - List XML Files After Enrichment
        run: ls -lh *.xml

      - name: Replace old EPG (if enrichment was successful)
        run: |
          if [ -f epg_updated.xml ]; then
            mv epg_updated.xml epg.xml
            echo "✅ Replaced epg.xml with enriched version."
          else
            echo "⚠️ epg_updated.xml not found. Skipping replacement."
          fi

      - name: Final Debug - List Files After Replacement
        run: ls -lh *.xml