name: Daily EPG Enrichment 

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2 AM UTC

jobs:
  enrich-epg:
    runs-on: ubuntu-latest

    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # You can adjust the version if needed

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx lxml  # Add other dependencies if needed

      - name: Backup previous EPG
        run: |
          cp epg.xml epg_yesterday.xml || true

      - name: Run enrich_epg.py script
        run: |
          python scripts/enrich_epg.py epg.xml epg_updated.xml \
            --async \
            --landscape-only \
            --language en \
            --target-channels 403788 403674 403837 403794 403620 403772 403655 403847 403576

      - name: Replace old EPG file
        run: |
          mv epg_updated.xml epg.xml