name: 📡 Daily EPG Enrichment + Notification

on:
  workflow_dispatch:      # ✅ This ensures the "Run workflow" button appears
  schedule:
    - cron: '0 4 * * *'   # 🕓 Runs daily at 04:00 UTC

jobs:
  enrich-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 📦 Install Python Dependencies
        run: |
          pip install aiohttp lxml requests

      - name: 🌐 Download Latest EPG
        run: curl -o epg.xml https://epg.pw/xmltv/epg_US.xml

      - name: 🧠 Step 1: Enrich EPG
        run: python3 scripts/add_epg_enrichment_async.py epg.xml epg_updated.xml ${{ secrets.TMDB_API_KEY }}

      - name: 🧼 Step 2: Replace Old EPG with Enriched Version
        run: |
          cp epg.xml epg_yesterday.xml || true
          mv epg_updated.xml epg.xml

      - name: 🎨 Step 3: Generate Genre List
        run: python3 scripts/generate_genres.py

      - name: 🆕 Step 4: Detect New Shows
        run: |
          if [ -f epg_yesterday.xml ]; then
            python3 scripts/notify_new_programs.py epg_yesterday.xml epg.xml
          else
            echo "No previous EPG to compare." > new_shows_notification.txt
          fi

      - name: 📲 Step 5: Send Pushbullet Notification to Redmi 13C
        run: python3 scripts/send_pushbullet_notification.py
        env:
          PUSHBULLET_TOKEN: ${{ secrets.PUSHBULLET_TOKEN }}

      - name: 💾 Step 6: Commit & Push Updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add epg.xml epg_yesterday.xml genres.xml new_shows_notification.txt
          git diff --cached --quiet || git commit -m "✅ Daily EPG Update with Notifications"
          git pull --rebase --autostash origin main
          git add .github/workflows/daily_epg_enrichment.yml
          git commit -m "🔁 Force workflow to register"
          git push
          # force GitHub to register workflow_dispatch

