name: Update EPG

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *"

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Copy old EPG if exists
        run: cp epg.xml epg_yesterday.xml || true

      - name: Enrich EPG
        run: |
          python scripts/enrich_epg.py epg.xml epg_updated.xml \
            --async \
            --landscape-only \
            --language en \
            --target-channels 403788 403674 403837 403794 403620 403772 403655 403847 403576
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}

      - name: Replace EPG
        run: mv epg_updated.xml epg.xml

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add epg.xml epg_yesterday.xml
          git commit -m "Update EPG on $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push