name: 📡 Daily EPG Enrichment

on:
  workflow_dispatch:    # ✅ Enables "Run workflow" button in GitHub UI
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 11 * * *'

jobs:
  enrich-epg:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🐍 Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: 📦 Install Python Dependencies
        run: |
          pip install aiohttp aiofiles xmltodict tqdm tmdbsimple requests

      - name: 🌐 Download US EPG from epg.pw
        run: python3 scripts/fetch_epg.py

      - name: Replace old EPG
        run: |
         echo "Replacing old EPG with latest epgshare01.online version..."
         rm -f epg.xml         # remove old EPG file if it exists
         mv epg.xml epg.xml  # rename the downloaded one


      - name: 🎨 Generate Genre List
        run: python3 scripts/generate_genres.py epg.xml
      
      - name: ✅ Commit & Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add epg.xml epg_yesterday.xml genres.xml
          git diff --cached --quiet || git commit -m "✅ Daily EPG Enrichment"
          git pull --rebase --autostash origin main
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
