name: Daily EPG Update

on:
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 04:00 UTC
  workflow_dispatch:      # Optional manual trigger

permissions:
  contents: write
  
jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download EPG from EPG.pw
      run: curl -sS https://epg.pw/xmltv/epg_US.xml -o epg.xml

    - name: Enrich EPG with Posters
      run: python3 scripts/add_posters.py epg.xml epg_updated.xml
      env:
        TMDB_API_KEY: 3c837d95cc9bd986bf230d9e12ba222a

    - name: Finalize update
      run: |
        mv epg_updated.xml epg.xml
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add epg.xml
        git diff-index --quiet HEAD || git commit -m "Daily EPG Update with Posters"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/gtvservices5/EPG.git
